### ISSUE TITLE
Code Review: Set up your Kanban board

### ISSUE THREAD

**Issue by grauJavier** [grauJavier/final-capstone-front-end#38]
### Links
- **Link for front-end Kanban Board:** https://github.com/grauJavier/final-capstone-front-end/projects/1
- **Link for back-end Kanban Board:** https://github.com/grauJavier/final-capstone-back-end/projects/1

### Students
- Student A: @Luffytaro22 // Manuel Sánchez
- Student B: @lRebornsl // Anthony Vásquez
- Student C: @grauJavier // Javier Grau

### Screenshots
**Back-End:**
![image](https://github.com/grauJavier/final-capstone-front-end/assets/127109669/3a6209f0-bc75-4cd3-98f2-7704ae076b25)

**Front-End:**
![image](https://github.com/grauJavier/final-capstone-front-end/assets/127109669/0527db26-65f1-4364-981d-214ea7b2fee5)

**Comment by Meltrust** [comment]
Hi @grauJavier,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees and pointings✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
